branches:
  only:
  - dev
  - master

skip_tags: true

skip_commits:
  files:
    - assets/*      
    - docs/*    

os: Visual Studio 2017

configuration: Release

nuget:
  project_feed: false
  disable_publish_on_pr: true

build_script:
- cmd: >-
    build

test: off

artifacts:
- path: 'artifacts\*.nupkg'